### ISSUE TITLE
移动端蒙层下底部页面穿透问题

### ISSUE THREAD

**Issue by arieslx** [arieslx/Blog#3]

**Comment by arieslx** [comment]
### 前情提要
移动端采用了网上各种方式
[禁止蒙层底部页面跟随滚动](https://segmentfault.com/a/1190000012313337)
直觉可能和库的文本流有关，某一坨东西撑开了body吧
然后一层一层的加`overflow:hidden`
最后在某一个组件上生效了，于是暴力操作
```tsx
className={this.state.isShow?'pageCurrentHidden': 'pageCurrentAuto'} // tsx文件
```
```css 

/* 控制overflow  css文件*/
.pageCurrentHidden .page-content{
    overflow: hidden;
}
.pageCurrentAuto .page-content{
    overflow: auto;
}
```
